name: Generate Snake & 3D Calendar

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Snake Graph
      - name: Generate Snake Graph
        uses: platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark

      # 3D Contribution Calendar
      - name: Generate 3D Contribution Calendar
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      # Copy outputs to dist/
      - name: Copy 3D Calendar
        run: |
          mkdir -p dist
          cp -r profile-3d-contrib/* dist/ || echo "No 3D calendar files found"

      # Commit and push both outputs
      - name: Push to output branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -B output
          git add dist
          git commit -m "Update snake and 3D calendar" || echo "No changes to commit"
          git push origin output --force
