name: Generate Snake & 3D Calendar

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      # 2️⃣ Horizontal Snake Graph
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark

      # 3️⃣ 3D Contribution Calendar
      - name: Generate 3D contribution calendar
        uses: yoshi389111/github-profile-3d-contrib@v0.7.1

      # 4️⃣ Debug — list generated files
      - name: List generated files
        run: ls -R dist || echo "dist folder not found"

      # 5️⃣ Push generated files to output branch
      - name: Push to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
