name: Generate Vertical Contribution Calendar

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Vertical Contribution Calendar
        uses: platane/snk@v3
        with:
          github_user_name: Shivam8286
          outputs: |
            dist/github-contribution-grid-snake-vertical-dark.svg?palette=github-dark&vertical=true

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
